POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "name":"Ariful Islam",
    "email": "ariful@gmail.com",
    "password": "pass123"
}

###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "ariful@gmail.com",
    "password": "pass123"
}

###
GET http://localhost:4000/public

###
GET http://localhost:4000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjQ2ZmIwYTA2ZDk3ZDhkNTliM2Q5MzMiLCJuYW1lIjoiQXJpZnVsIElzbGFtIiwiZW1haWwiOiJhcmlmdWxAZ21haWwuY29tIiwiaWF0IjoxNjQ4ODI0NjY4LCJleHAiOjE2NDg4MzE4Njh9.qgJ1fzvH8QHP5-j5Jmz6-QwtDeB6Wx1VhYjUjfJ1Pgg

